version: '3.8'
services:
  db:
    image: postgres:12
    ports:
      - '5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  web:
    build:
      dockerfile: Dockerfile
    command: rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    depends_on:
      - db
    ports:
      - "3001:3001"
